<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 dark:text-gray-200 leading-tight">
            {{ __('Video') }}
        </h2>
    </x-slot>

    <div class="card">
        <div class="card-header">
                <div data-module="photo/upload" class="form-group float-left">
                    <a href="{{route('assets.video.add')}}" class="btn btn-sm btn-primary">
                        <i class="fa fa-plus"></i> Tambah video
                    </a>
                    <a href="{{route('assets.photo.index')}}" class="btn btn-default btn-sm"><i
                            class="fa fa-reload"></i> Refresh</a>
                </div>
                <div class="float-right">
                    <div class="form-inline">
                        <div class="form-group">
                            <select name="uploader" class=" form-control input-sm">
                                <option value="0">- All -</option>
                                <option value="428">20 Jam</option>
                                <option value="506">24 Jam</option>
                                <option value="175">Abchannel Id</option>
                                <option value="142">About Malang</option>
                                <option value="415">Aceh Nomics</option>
                                <option value="394">Aceh Timur Satu</option>
                                <option value="683">Ada Warta</option>
                                <option value="244">Adatah</option>
                                <option value="252">Agamnews Today</option>
                                <option value="117">Agromedicine</option>
                                <option value="58">Agtv News</option>
                                <option value="205">Akarsari</option>
                                <option value="554">Aktaduma</option>
                                <option value="662">Aktualkan</option>
                                <option value="956">Alif News</option>
                                <option value="905">Alinea Berita</option>
                                <option value="191">Alonesia</option>
                                <option value="732">Alowarta</option>
                                <option value="640">Alur Informasi</option>
                                <option value="482">Amoeba News</option>
                                <option value="914">Analis News</option>
                                <option value="867">Aneka Indonesia</option>
                                <option value="154">Anti Metri</option>
                                <option value="778">Arah Pandang</option>
                                <option value="779">Arah Pena</option>
                                <option value="811">Asimetris Media</option>
                                <option value="109">Aspirasiku</option>
                                <option value="89">Aswaja News</option>
                                <option value="368">Aurora News</option>
                                <option value="761">Axioma</option>
                                <option value="79">Ayo Bandung</option>
                                <option value="38">Ayo Banten</option>
                                <option value="37">Ayo Batang</option>
                                <option value="30">Ayo Bekasi</option>
                                <option value="31">Ayo Bogor</option>
                                <option value="94">Ayo Cirebon</option>
                                <option value="1">Ayo Indonesia</option>
                                <option value="76">Ayo Jakarta</option>
                                <option value="74">Ayo Kampus</option>
                                <option value="529">Ayo Kediri</option>
                                <option value="48">Ayo Malang</option>
                                <option value="35">Ayo Medan</option>
                                <option value="36">Ayo Palembang</option>
                                <option value="49">Ayo Pontianak</option>
                                <option value="32">Ayo Purwakarta</option>
                                <option value="77">Ayo Semarang</option>
                                <option value="170">Ayo Solo</option>
                                <option value="78">Ayo Surabaya</option>
                                <option value="33">Ayo Tasik</option>
                                <option value="34">Ayo Tegal</option>
                                <option value="532">Ayo Tekno</option>
                                <option value="531">Ayo Vibes</option>
                                <option value="39">Ayo Yogya</option>
                                <option value="468">Baaca Id</option>
                                <option value="364">Babad Id</option>
                                <option value="580">Bacabe Id</option>
                                <option value="881">Bacagituloh</option>
                                <option value="463">Bahana Rakyat</option>
                                <option value="581">Bakolantang</option>
                                <option value="631">Balanesia</option>
                                <option value="933">Bali Populer</option>
                                <option value="795">Bali Tren</option>
                                <option value="350">Balikpapan City</option>
                                <option value="901">Baliwara</option>
                                <option value="240">Bandar Lampung Post</option>
                                <option value="632">Bandung Hits</option>
                                <option value="893">Bandung Insider</option>
                                <option value="975">Bandung News</option>
                                <option value="196">Bandung News Photo</option>
                                <option value="369">Bangbara</option>
                                <option value="755">Bangkalan Network</option>
                                <option value="345">Banjarese</option>
                                <option value="234">Banten Ekspose</option>
                                <option value="678">Banten Hay</option>
                                <option value="466">Banten Network</option>
                                <option value="127">Banten Raya</option>
                                <option value="649">Banyumas Terkini</option>
                                <option value="332">Banyuwangi Network</option>
                                <option value="681">Banyuwangipedia</option>
                                <option value="1007">Barlingmas Media</option>
                                <option value="168">Basis 13</option>
                                <option value="642">Batam Ekbis</option>
                                <option value="805">Batas Timor</option>
                                <option value="998">Batu Network</option>
                                <option value="148">Bawa Kalem</option>
                                <option value="202">Bebas Baru</option>
                                <option value="684">Begaye Pontianak</option>
                                <option value="338">Bekasi Kinian</option>
                                <option value="711">Belanga</option>
                                <option value="166">Beranda Kita</option>
                                <option value="378">Berita Baik</option>
                                <option value="319">Berita Jowo</option>
                                <option value="187">Berita Karya</option>
                                <option value="235">Berita Karya Id</option>
                                <option value="199">Berita Nusra</option>
                                <option value="64">Berita Senator</option>
                                <option value="585">Berita Tokoh</option>
                                <option value="475">Berita Tren</option>
                                <option value="512">Berita Utama</option>
                                <option value="583">Berita Wisata</option>
                                <option value="59">Berita Yudha</option>
                                <option value="387">beritabulukumba.com</option>
                                <option value="511">Beritaria</option>
                                <option value="296">Bershalawat</option>
                                <option value="439">Bertaji</option>
                                <option value="495">Best Seller</option>
                                <option value="229">Betawi Pos</option>
                                <option value="994">Bharata</option>
                                <option value="455">Bibir Pasifik</option>
                                <option value="42">Bicara Berita</option>
                                <option value="61">Bicara Jabar</option>
                                <option value="295">Bicara Network</option>
                                <option value="145">Bicaralah</option>
                                <option value="970">Bidik Tangsel</option>
                                <option value="1020">Bilik Riau</option>
                                <option value="293">Bincang Korea</option>
                                <option value="346">Bingkai Nasional</option>
                                <option value="785">Bintara</option>
                                <option value="307">Bisnika</option>
                                <option value="398">Bisnis Bandung</option>
                                <option value="1008">Biznis Linggau</option>
                                <option value="733">Blitar Network</option>
                                <option value="1002">Blitar Network</option>
                                <option value="885">Blitar Terkini</option>
                                <option value="226">Blitnews</option>
                                <option value="259">Blits News</option>
                                <option value="563">Bogor Insider</option>
                                <option value="774">Bogor Prime</option>
                                <option value="110">Bogor Times</option>
                                <option value="746">Bojonegoro Network</option>
                                <option value="553">Bola Nusantara</option>
                                <option value="911">Bolinggo Tv</option>
                                <option value="182">Bondowoso Network</option>
                                <option value="479">Bonser News</option>
                                <option value="1028">Borneo Globe</option>
                                <option value="910">Borneo Street</option>
                                <option value="313">BPKP news</option>
                                <option value="694">Braga Pos</option>
                                <option value="349">Bribin News</option>
                                <option value="200">Britakan</option>
                                <option value="838">Bromo Today</option>
                                <option value="804">Buletin Jabar</option>
                                <option value="937">Busurnusa</option>
                                <option value="966">ByTrendz</option>
                                <option value="775">Cakrawala</option>
                                <option value="628">Catatan Bandung</option>
                                <option value="809">Catatan Fakta</option>
                                <option value="448">Ceklis Biru</option>
                                <option value="639">Celebes Network</option>
                                <option value="321">CEO Aceh</option>
                                <option value="854">Cepat Update</option>
                                <option value="53">Cerita Depok</option>
                                <option value="991">Cerita Today</option>
                                <option value="271">Ceritanews</option>
                                <option value="1016">Cerito Jambi</option>
                                <option value="989">Channel Jatim</option>
                                <option value="965">Cianjur Today</option>
                                <option value="389">Ciayumajakuning</option>
                                <option value="483">Cibungkul</option>
                                <option value="412">Cirebon Ekspres</option>
                                <option value="699">Cirebon Network</option>
                                <option value="437">Cirebon Raya</option>
                                <option value="794">Cirebon Times</option>
                                <option value="251">Ciremai News</option>
                                <option value="300">Cover Both Side</option>
                                <option value="279">Dagang Berita</option>
                                <option value="877">Daily Notif</option>
                                <option value="556">Daily Pangandaran</option>
                                <option value="1015">Delik Jabar</option>
                                <option value="308">Depok Today</option>
                                <option value="725">Detail</option>
                                <option value="928">Detak Terkini</option>
                                <option value="370">Detik 60</option>
                                <option value="974">Detik Sumsel</option>
                                <option value="899">Dewantara News</option>
                                <option value="672">Dewata Network</option>
                                <option value="575">Dhaha News</option>
                                <option value="138">Diatas Roda</option>
                                <option value="902">Dicintai</option>
                                <option value="275">Digitalbank.id</option>
                                <option value="980">Dikasih Info</option>
                                <option value="504">Dio Tv</option>
                                <option value="183">Diorama</option>
                                <option value="450">Diseduh</option>
                                <option value="382">Distrik News</option>
                                <option value="558">Djakarta Nexus</option>
                                <option value="348">DKlik News</option>
                                <option value="318">DKYLB</option>
                                <option value="646">Dnews Star</option>
                                <option value="93">Dobrak</option>
                                <option value="619">Draf Tekno</option>
                                <option value="473">Dunia Anak Indonesia</option>
                                <option value="540">Edaran ID</option>
                                <option value="97">Edisi</option>
                                <option value="880">Edu Historia</option>
                                <option value="297">Ekbis Tangsel</option>
                                <option value="560">Elbait Sukabumi</option>
                                <option value="125">Enam Pagi</option>
                                <option value="152">eNBe Indonesia</option>
                                <option value="3">Esn Banten</option>
                                <option value="518">Esportsku</option>
                                <option value="411">Etnologi Media</option>
                                <option value="133">Fajar Banten</option>
                                <option value="505">Fajar Nusa</option>
                                <option value="266">Fakta IDN</option>
                                <option value="634">Financial Review</option>
                                <option value="327">Fismedia</option>
                                <option value="627">Florata News</option>
                                <option value="397">Flores Editorial</option>
                                <option value="499">Flores News</option>
                                <option value="707">FNN</option>
                                <option value="87">Fokus Berita</option>
                                <option value="826">Fokus Blora</option>
                                <option value="551">Fokus Jepara</option>
                                <option value="451">Fokus Kudus</option>
                                <option value="621">Fokus Media</option>
                                <option value="310">Fokus Muria</option>
                                <option value="452">Fokus Pati</option>
                                <option value="756">Fokus Pekalongan</option>
                                <option value="625">Fokus Rembang</option>
                                <option value="95">Fokus Satu</option>
                                <option value="626">Fokus Semarang</option>
                                <option value="669">Fokus Solo</option>
                                <option value="668">Fokus Surabaya</option>
                                <option value="569">For Sains</option>
                                <option value="159">Formas</option>
                                <option value="102">Formas News</option>
                                <option value="710">Fox Bandung</option>
                                <option value="289">Frekuensinews</option>
                                <option value="599">Gala Lisan</option>
                                <option value="876">Galeri Sumba</option>
                                <option value="299">Gamenosida</option>
                                <option value="500">Gang Berita</option>
                                <option value="264">Gardunesia</option>
                                <option value="1029">Garton News</option>
                                <option value="816">Garuda Revolution</option>
                                <option value="686">Garut Inside</option>
                                <option value="114">Geliat Ekonomi</option>
                                <option value="408">Gen Z Daily</option>
                                <option value="960">Genmilenial</option>
                                <option value="872">Gerbang Nalar</option>
                                <option value="363">Gerbang Network</option>
                                <option value="377">Girinesia</option>
                                <option value="85">Giwangkara</option>
                                <option value="245">Go Depok</option>
                                <option value="100">Gora Juara</option>
                                <option value="462">Grage News</option>
                                <option value="744">Gresik Network</option>
                                <option value="149">Gunem Id</option>
                                <option value="157">Gunyam</option>
                                <option value="391">Habaritah</option>
                                <option value="63">Hai Bandung</option>
                                <option value="526">Hai Jabar</option>
                                <option value="360">Haji Umrah News</option>
                                <option value="56">Hallo Banten</option>
                                <option value="73">Hallo Bisnis</option>
                                <option value="111">Hallo Bogor</option>
                                <option value="44">Hallo Depok</option>
                                <option value="124">Hallo Desa</option>
                                <option value="28">Hallo Id</option>
                                <option value="230">Hallo Jakarta</option>
                                <option value="55">Hallo Jatim</option>
                                <option value="57">Hallo Lampung</option>
                                <option value="179">Hallo Lifestyle</option>
                                <option value="72">Hallo Madura</option>
                                <option value="54">Hallo Malang</option>
                                <option value="231">Hallo Purwasuka</option>
                                <option value="45">Hallo Seleb</option>
                                <option value="136">Hallo Sidoarjo</option>
                                <option value="131">Hallo Sport</option>
                                <option value="46">Hallo Sukabumi</option>
                                <option value="128">Hallo Sulsel</option>
                                <option value="135">Hallo Sultra</option>
                                <option value="47">Hallo Tasik</option>
                                <option value="186">Hallo Ternate</option>
                                <option value="676">Hallyu Vibe</option>
                                <option value="1006">Halo GenZ</option>
                                <option value="576">Halo Pedeka</option>
                                <option value="203">Halo Pelajar</option>
                                <option value="219">Haluan Aceh</option>
                                <option value="225">Haluan Banten</option>
                                <option value="238">Haluan Bengkulu</option>
                                <option value="256">Haluan Bogor</option>
                                <option value="214">Haluan Jabar</option>
                                <option value="215">Haluan Jakarta</option>
                                <option value="223">Haluan Jambi</option>
                                <option value="216">Haluan Jateng</option>
                                <option value="222">Haluan Jatim</option>
                                <option value="258">Haluan Kalbar</option>
                                <option value="257">Haluan Kalsel</option>
                                <option value="107">Haluan Kaltim</option>
                                <option value="13">Haluan Kepri</option>
                                <option value="561">Haluan kita</option>
                                <option value="197">Haluan Lampung</option>
                                <option value="218">Haluan Medan</option>
                                <option value="106">Haluan Padang</option>
                                <option value="11">Haluan Riau</option>
                                <option value="217">Haluan Sulsel</option>
                                <option value="220">Haluan Sulteng</option>
                                <option value="221">Haluan Sumsel</option>
                                <option value="758">Harian Bolmong Raya</option>
                                <option value="10">Harian Haluan</option>
                                <option value="242">Harian Jember</option>
                                <option value="236">Harian Kami</option>
                                <option value="810">Harian Kripto</option>
                                <option value="27">Harian Massa Id</option>
                                <option value="942">Harian Memo Kepri</option>
                                <option value="40">Harian Merapi</option>
                                <option value="101">Harian Sederhana</option>
                                <option value="274">Harian Terbit</option>
                                <option value="550">Harmas News</option>
                                <option value="935">Hei Pop</option>
                                <option value="792">Helly Media</option>
                                <option value="908">Helo Berita</option>
                                <option value="443">Hi Timur</option>
                                <option value="657">Hits IDN</option>
                                <option value="294">Hops ID</option>
                                <option value="817">Hot Lombok</option>
                                <option value="460">Hukama News</option>
                                <option value="964">Hulondalo</option>
                                <option value="773">Ibarat</option>
                                <option value="494">Id Jatim</option>
                                <option value="227">Id Post</option>
                                <option value="323">ID Times</option>
                                <option value="517">Ide Indonesiaku</option>
                                <option value="562">Ide Nusantara</option>
                                <option value="863">IdFeeds</option>
                                <option value="952">Idisi Online</option>
                                <option value="682">Ihwal</option>
                                <option value="695">Ijen Indonesia</option>
                                <option value="798">IN Indonesia</option>
                                <option value="874">In Riau</option>
                                <option value="873">In Sulut</option>
                                <option value="276">Independen Media</option>
                                <option value="315">Independensia</option>
                                <option value="62">Indikator News</option>
                                <option value="891">Indo Insider</option>
                                <option value="578">Indo Rakyat</option>
                                <option value="868">Indomostviral.com</option>
                                <option value="1021">Indonesia Berita</option>
                                <option value="720">Indonesia Daily</option>
                                <option value="869">Indonesia Folks</option>
                                <option value="99">Indonesia News</option>
                                <option value="366">Indonesia Trends</option>
                                <option value="940">Indonesian Channel</option>
                                <option value="789">Indoneside</option>
                                <option value="273">Indonews Today</option>
                                <option value="322">Indotren</option>
                                <option value="1011">Info 1</option>
                                <option value="737">Info Dinamis</option>
                                <option value="961">Info Indonesia</option>
                                <option value="813">Info Liga</option>
                                <option value="121">Info Redaksi</option>
                                <option value="492">Info Spesifikasi</option>
                                <option value="362">Info Sumsel</option>
                                <option value="212">Info Terkini 24</option>
                                <option value="996">Inforia</option>
                                <option value="194">Ingon Ingon</option>
                                <option value="516">Ini Bengkulu</option>
                                <option value="401">Ini Data</option>
                                <option value="865">Ini Kebumen</option>
                                <option value="595">Ini Palu</option>
                                <option value="584">Inilah Bandung</option>
                                <option value="91">Inilah Jogja</option>
                                <option value="118">Inilah Koran</option>
                                <option value="119">Inilahnews</option>
                                <option value="955">Initrends</option>
                                <option value="958">Injurnal</option>
                                <option value="367">Innalar</option>
                                <option value="917">InNewsPedia</option>
                                <option value="454">Inside Pontianak</option>
                                <option value="396">Insiden 24</option>
                                <option value="381">Inspiranesia</option>
                                <option value="954">Inspirasi Nusantara</option>
                                <option value="171">Inspiratio Media</option>
                                <option value="416">InSulteng</option>
                                <option value="653">Intinesia</option>
                                <option value="406">Islamadania</option>
                                <option value="444">Ivok News</option>
                                <option value="703">Jabar Berdaya</option>
                                <option value="498">Jabar hits</option>
                                <option value="280">Jabar Juara</option>
                                <option value="281">Jabar Juara Bandung</option>
                                <option value="282">Jabar Juara Cirebon</option>
                                <option value="283">Jabar Juara Tasikmalaya</option>
                                <option value="173">Jabar News</option>
                                <option value="724">Jabar Style</option>
                                <option value="630">Jabar Tranding</option>
                                <option value="269">Jabariber News</option>
                                <option value="69">Jabodetabek Id</option>
                                <option value="438">Jabotabek Update</option>
                                <option value="870">Jadi Tau</option>
                                <option value="162">Jakarta Daily</option>
                                <option value="693">Jakarta Daily Indonesia</option>
                                <option value="731">Jakarta Insider</option>
                                <option value="521">Jakarta Netizen</option>
                                <option value="536">Jakarta Trend</option>
                                <option value="1031">Jakarta Voice</option>
                                <option value="700">Jakbarnews</option>
                                <option value="705">Jakpus News</option>
                                <option value="706">Jaktim News</option>
                                <option value="979">Jalur Info Sulbar</option>
                                <option value="820">Jam Pasir</option>
                                <option value="644">Jambi Oke</option>
                                <option value="728">Jambi Seru</option>
                                <option value="589">Jambi Siber</option>
                                <option value="469">Jampang Pedia</option>
                                <option value="659">Jangkara</option>
                                <option value="830">Jangkara Jabar</option>
                                <option value="831">Jangkara Jakarta</option>
                                <option value="828">Jangkara Jateng</option>
                                <option value="832">Jangkara Jatim</option>
                                <option value="829">Jangkara Lampung</option>
                                <option value="827">Jangkara Sulsel</option>
                                <option value="555">Jangkau Indonesia</option>
                                <option value="988">Jaring News</option>
                                <option value="284">Jateng Network</option>
                                <option value="356">Jateng Post</option>
                                <option value="882">Jatim Hari Ini</option>
                                <option value="43">Jatim Network</option>
                                <option value="392">Jatim Zone</option>
                                <option value="165">Jejak Sulsel</option>
                                <option value="922">Jejakini</option>
                                <option value="51">Jember Network</option>
                                <option value="514">Jendela Indonesia</option>
                                <option value="821">Jendela Psikologia</option>
                                <option value="436">Jogja Intens</option>
                                <option value="638">Jogja Raya</option>
                                <option value="864">Joglo Media</option>
                                <option value="742">Jombang Network</option>
                                <option value="806">Journal Nusantara</option>
                                <option value="799">Jurnal Baca</option>
                                <option value="667">Jurnal Elite</option>
                                <option value="776">Jurnal Flores</option>
                                <option value="647">Jurnal Garut</option>
                                <option value="727">Jurnal Metropolitan</option>
                                <option value="430">Jurnal News</option>
                                <option value="714">Jurnal Pro</option>
                                <option value="985">Jurnal Style</option>
                                <option value="447">Jurnal Tinta</option>
                                <option value="414">Jurnal warga</option>
                                <option value="766">Jurnalindo</option>
                                <option value="98">Jurnalis News</option>
                                <option value="845">Jurnalisme News</option>
                                <option value="423">Justisia News</option>
                                <option value="593">Kabar Alam</option>
                                <option value="906">Kabar Buana</option>
                                <option value="113">Kabar Fajar</option>
                                <option value="596">Kabar ID</option>
                                <option value="189">Kabar Inspirasi</option>
                                <option value="796">Kabar Inspirasi Jabar</option>
                                <option value="591">Kabar Jambi Kito</option>
                                <option value="671">Kabar Jambi Update</option>
                                <option value="666">Kabar Lumajang</option>
                                <option value="433">Kabar NTT</option>
                                <option value="400">Kabar Pesisir</option>
                                <option value="417">Kabar Prioritas</option>
                                <option value="2">Kabar Rakyat</option>
                                <option value="765">Kabar Sulteng</option>
                                <option value="1017">Kabar4</option>
                                <option value="139">Kabarku</option>
                                <option value="501">Kalimantan Satu</option>
                                <option value="620">Kalimantan Update</option>
                                <option value="351">Kalteng Lima</option>
                                <option value="918">Kanal Baru</option>
                                <option value="172">Kanal Jateng</option>
                                <option value="920">Kanal One</option>
                                <option value="929">Kanal Suara</option>
                                <option value="144">Kata Logika</option>
                                <option value="161">Katolikku</option>
                                <option value="306">Kebaca</option>
                                <option value="753">Kediri Network</option>
                                <option value="981">Kelumajang</option>
                                <option value="986">Kepodeh</option>
                                <option value="247">Kesatu</option>
                                <option value="248">Ketapel News</option>
                                <option value="855">KetapelNews.com</option>
                                <option value="301">Ketik News</option>
                                <option value="959">Ketik Pos</option>
                                <option value="147">Khatulistiwa Update</option>
                                <option value="418">Khazanahimani</option>
                                <option value="372">Kiat Indonesia</option>
                                <option value="23">Kicau Jabar</option>
                                <option value="24">Kicau Jakarta</option>
                                <option value="25">Kicau Jateng</option>
                                <option value="26">Kicau Jatim</option>
                                <option value="22">Kicau Kicau</option>
                                <option value="477">Kilas</option>
                                <option value="320">Kilas Berita</option>
                                <option value="822">Kilas Kediri Raya</option>
                                <option value="743">Kilas Kepri</option>
                                <option value="844">Kilat</option>
                                <option value="1009">Kilat Jateng</option>
                                <option value="993">Kilat Medan</option>
                                <option value="1032">Kilat Papua</option>
                                <option value="1005">Kilat Purwakarta</option>
                                <option value="1026">Kilat Semarang</option>
                                <option value="1030">Kilat Solo</option>
                                <option value="990">Kilat Tapanuli</option>
                                <option value="1018">Kilat Tegal</option>
                                <option value="262">Kilau Lampung</option>
                                <option value="66">Klik Aktual</option>
                                <option value="115">Klik Anggaran</option>
                                <option value="730">Klik Banjarnegara</option>
                                <option value="982">Klik Halmahera</option>
                                <option value="449">Klik Indonesia</option>
                                <option value="542">Klik Labuanbajo</option>
                                <option value="651">Klik Lombok</option>
                                <option value="461">Klik Manado</option>
                                <option value="298">Klik Medianet</option>
                                <option value="852">Klik Medianet</option>
                                <option value="358">Klik Pendidikan</option>
                                <option value="717">Klik Read</option>
                                <option value="983">Klik Saja</option>
                                <option value="690">Klik Semarang</option>
                                <option value="729">Klik Times</option>
                                <option value="465">Kobaran</option>
                                <option value="615">Koneksi Indonesia</option>
                                <option value="407">Konstruksi.co.id</option>
                                <option value="65">Konten Jateng</option>
                                <option value="704">Konten Network</option>
                                <option value="587">Koran Gala</option>
                                <option value="192">Koran Memo</option>
                                <option value="376">Koran Saku</option>
                                <option value="302">Korea Banget</option>
                                <option value="916">Kpop Chart</option>
                                <option value="177">Kreasi Parenting</option>
                                <option value="303">Kulinear</option>
                                <option value="70">Kulturnativ</option>
                                <option value="654">Kunci Jawabanku</option>
                                <option value="780">Kurawal Media</option>
                                <option value="871">Kvibes</option>
                                <option value="270">Labuhanbaturaya</option>
                                <option value="442">Laju Pantura</option>
                                <option value="610">Lambe Kriminal</option>
                                <option value="741">Lamongan Network</option>
                                <option value="997">Lamongan Network</option>
                                <option value="533">Lampung Ekspose</option>
                                <option value="825">Lampung Pride</option>
                                <option value="927">Lampung Time</option>
                                <option value="613">Lampungnesia</option>
                                <option value="987">Laras Post</option>
                                <option value="239">Laros Media</option>
                                <option value="781">Lembang News</option>
                                <option value="253">Lensa Banten</option>
                                <option value="285">Lensa Purwakarta</option>
                                <option value="984">Lensanesia</option>
                                <option value="228">Lentera Times</option>
                                <option value="261">Libernesia</option>
                                <option value="574">Lihat Jambi</option>
                                <option value="404">Lintas Ide</option>
                                <option value="655">Lintas Papua</option>
                                <option value="193">Lintas Pewarta</option>
                                <option value="126">Liputan Bekasi</option>
                                <option value="361">Liputan Kendal Terkini</option>
                                <option value="312">Lirik Lagu Hits</option>
                                <option value="770">Literasi Network</option>
                                <option value="155">Lombok Insider</option>
                                <option value="180">Lumajang Network</option>
                                <option value="326">Mabar News</option>
                                <option value="738">Madiun Network</option>
                                <option value="324">Maduramu</option>
                                <option value="752">Magetan Network</option>
                                <option value="784">Maha Gabut</option>
                                <option value="764">Mahasiswa Talk</option>
                                <option value="211">Mahidara</option>
                                <option value="787">Make Nyus</option>
                                <option value="379">Malang Network</option>
                                <option value="999">Maluku Network</option>
                                <option value="263">Malut Network</option>
                                <option value="833">Manadonesia</option>
                                <option value="783">Manggarai News</option>
                                <option value="972">Manuskrip Magazine</option>
                                <option value="802">Mari Bicara News</option>
                                <option value="314">Masagipedia</option>
                                <option value="915">Mata Delta</option>
                                <option value="249">Maung Bandung</option>
                                <option value="903">Medan Insider</option>
                                <option value="1019">Medanesia</option>
                                <option value="1014">Media Ekspres</option>
                                <option value="661">Media Jambi News</option>
                                <option value="15">Media Kepri</option>
                                <option value="103">Media Kepri Co</option>
                                <option value="597">Media Labuan Bajo</option>
                                <option value="592">Media Priangan</option>
                                <option value="1003">Media Promed</option>
                                <option value="963">Media Sungailiat</option>
                                <option value="224">Medianekita</option>
                                <option value="50">Medium Co</option>
                                <option value="132">Medius News</option>
                                <option value="849">Melansir</option>
                                <option value="712">Melenggang</option>
                                <option value="664">Mengerti</option>
                                <option value="892">Menit 24</option>
                                <option value="842">Metro Aspirasiku</option>
                                <option value="818">Metro NTB</option>
                                <option value="919">Metro Satu</option>
                                <option value="812">Metro Selebes</option>
                                <option value="519">Metro Sulteng</option>
                                <option value="353">Metronesia</option>
                                <option value="953">Metropolitan</option>
                                <option value="277">Mikrofon Id</option>
                                <option value="1027">Mining Insider</option>
                                <option value="105">Mitra News</option>
                                <option value="623">Mocosik</option>
                                <option value="967">Moeslim Choice</option>
                                <option value="866">Mojokerto Network</option>
                                <option value="992">Moremedia Id</option>
                                <option value="188">Muda Bahagia</option>
                                <option value="496">Muda Belia</option>
                                <option value="523">Multaqomedia</option>
                                <option value="622">Muria Network</option>
                                <option value="426">Muslim Kita</option>
                                <option value="90">Muslim Terkini</option>
                                <option value="304">Muslima</option>
                                <option value="490">My Sulut</option>
                                <option value="808">Nara Bandung</option>
                                <option value="151">Nara Times</option>
                                <option value="539">Nasional ID</option>
                                <option value="624">Nasionalita</option>
                                <option value="432">Naskah ID</option>
                                <option value="696">Naung Id</option>
                                <option value="292">Naver IDN</option>
                                <option value="1012">Neti Talk</option>
                                <option value="60">News Media</option>
                                <option value="336">Newspro</option>
                                <option value="237">Newz Eka</option>
                                <option value="359">Ngaderes</option>
                                <option value="745">Nganjuk Network</option>
                                <option value="734">Ngawi Network</option>
                                <option value="130">Nol Meter</option>
                                <option value="431">Nongkrong</option>
                                <option value="629">Notif Indonesia</option>
                                <option value="515">NTB Pos</option>
                                <option value="424">NTT Express</option>
                                <option value="577">NTT Hits</option>
                                <option value="470">Nuansa Berita</option>
                                <option value="278">Nuansa Sinar</option>
                                <option value="819">Nuansa Timur</option>
                                <option value="552">Nules</option>
                                <option value="557">Nunmedia Id</option>
                                <option value="616">Nusa Hits</option>
                                <option value="771">Nusa Times</option>
                                <option value="371">Nusantara 62</option>
                                <option value="347">Nusawara</option>
                                <option value="851">Nusra Inside</option>
                                <option value="198">Nyarink</option>
                                <option value="446">Obat News</option>
                                <option value="757">Obseshe</option>
                                <option value="420">Ok Oce News</option>
                                <option value="507">Oke Indonesia</option>
                                <option value="508">Oke jabar</option>
                                <option value="510">Oke Jateng</option>
                                <option value="509">Oke Jatim</option>
                                <option value="716">Oke Narasi</option>
                                <option value="900">Okeguys</option>
                                <option value="476">Okenusra</option>
                                <option value="488">Okey Bro</option>
                                <option value="572">Old Kabar Jambi Kito</option>
                                <option value="888">Olenas</option>
                                <option value="541">Orand Maybe</option>
                                <option value="571">Orbid Id</option>
                                <option value="544">Orbit Indonesia</option>
                                <option value="675">Osingpedia</option>
                                <option value="75">Otojurnalisme</option>
                                <option value="81">Otonetters</option>
                                <option value="233">Otosportif</option>
                                <option value="383">Otostar</option>
                                <option value="82">Otowheel</option>
                                <option value="84">Otoxplore</option>
                                <option value="857">Our Indonesia</option>
                                <option value="747">Pacitan Network</option>
                                <option value="786">Pakabar</option>
                                <option value="762">Palima</option>
                                <option value="606">Palopo leaks</option>
                                <option value="736">Pamekasan Network</option>
                                <option value="163">Pandeglang News</option>
                                <option value="715">Pandu Rakyat</option>
                                <option value="677">Pangandaran Today</option>
                                <option value="886">Pantura Network</option>
                                <option value="760">Pantura Raya</option>
                                <option value="316">Pantura Talk</option>
                                <option value="797">Pantura Times</option>
                                <option value="373">Papan Skor</option>
                                <option value="713">Parada Pos</option>
                                <option value="547">Pasal ID</option>
                                <option value="754">Pasuruan Network</option>
                                <option value="456">Pati Update</option>
                                <option value="335">Pedoman Rakyat News</option>
                                <option value="837">Pejuang Kantoran</option>
                                <option value="524">Pelita Pengetahuan</option>
                                <option value="697">Pemberitaan Id</option>
                                <option value="708">Pembrita Betawi</option>
                                <option value="206">Pena Bicara</option>
                                <option value="427">Pena Times</option>
                                <option value="889">Pengabar</option>
                                <option value="190">Penjedar</option>
                                <option value="478">Pensil Biru</option>
                                <option value="481">Pentingpedia</option>
                                <option value="858">Penulis Pro</option>
                                <option value="924">Pepo</option>
                                <option value="546">Perbarui</option>
                                <option value="768">Pers Today</option>
                                <option value="374">Petromax News</option>
                                <option value="685">Pijar Nusantara</option>
                                <option value="815">Pilihan indonesia</option>
                                <option value="648">Poinfomedia</option>
                                <option value="169">Pojok Durasi</option>
                                <option value="88">Pojok Madura</option>
                                <option value="122">Pojok Malioboro</option>
                                <option value="204">Pojok Semarang</option>
                                <option value="749">Ponorogo Network</option>
                                <option value="718">Pontianak Globe</option>
                                <option value="887">Poper Land</option>
                                <option value="167">Poros</option>
                                <option value="957">Poros Ampera</option>
                                <option value="330">Portal Amanah</option>
                                <option value="241">Portal Banyuwangi</option>
                                <option value="537">Portal Baraya</option>
                                <option value="883">Portal Indramayu</option>
                                <option value="660">Portal Jember</option>
                                <option value="607">Portal Manggarai</option>
                                <option value="884">Portal Musi Rawas</option>
                                <option value="67">Portal Republik</option>
                                <option value="601">Portal Salatiga</option>
                                <option value="663">Portal Seleb</option>
                                <option value="29">Portal Siber</option>
                                <option value="573">Portal Tebo</option>
                                <option value="208">Portal Yogya</option>
                                <option value="441">Pos Flores</option>
                                <option value="722">Postrend</option>
                                <option value="405">Pro Nusantara</option>
                                <option value="636">Pro Jateng</option>
                                <option value="656">Pro Jatim</option>
                                <option value="689">Pro Serang</option>
                                <option value="750">Probolinggo Network</option>
                                <option value="947">Programanesia</option>
                                <option value="836">ProIKN</option>
                                <option value="354">ProJabar</option>
                                <option value="250">Promilenial</option>
                                <option value="480">Protechnesia</option>
                                <option value="243">Protokol24</option>
                                <option value="588">Publika NTB</option>
                                <option value="520">Punya Rakyat</option>
                                <option value="658">Purbalingga Terkini</option>
                                <option value="614">Purwakarta Hits</option>
                                <option value="425">Purwakarta Online</option>
                                <option value="709">Purwokerto Insight</option>
                                <option value="486">Pustaka</option>
                                <option value="665">Quena</option>
                                <option value="945">Radar Cianjur</option>
                                <option value="946">Radar Depok</option>
                                <option value="951">Radar Jabar</option>
                                <option value="1013">Radar Karawang</option>
                                <option value="949">Radar Sukabumi</option>
                                <option value="80">Radio Web Indo</option>
                                <option value="565">Ragam Bali</option>
                                <option value="527">Ragam Bandung</option>
                                <option value="641">Ragam Banggai</option>
                                <option value="445">Ragam Indonesia</option>
                                <option value="525">Ragam Jakarta</option>
                                <option value="567">Ragam Lombok</option>
                                <option value="568">Ragam Mandalika</option>
                                <option value="670">Ragam Palu</option>
                                <option value="564">Ragam Semarang</option>
                                <option value="605">Ragam Sulteng</option>
                                <option value="604">Ragam Sulut</option>
                                <option value="971">Ragam Sumsel</option>
                                <option value="528">Ragam Surabaya</option>
                                <option value="502">Ragam Yogyakarta</option>
                                <option value="950">Rahasia Gadis</option>
                                <option value="403">Rajawali News</option>
                                <option value="201">Rakyat Bali</option>
                                <option value="1023">Rakyat Karawang</option>
                                <option value="143">Rakyat Priangan</option>
                                <option value="944">RBG.id</option>
                                <option value="96">Realita Publik</option>
                                <option value="1024">Realitas Online</option>
                                <option value="140">Referensi Berita</option>
                                <option value="879">Rekan Media</option>
                                <option value="493">Rekomendasi</option>
                                <option value="890">Relevania</option>
                                <option value="926">Relung</option>
                                <option value="566">Reportase Banten</option>
                                <option value="635">Riau Liputan</option>
                                <option value="1025">Riau Makmur</option>
                                <option value="12">Riau Mandiri</option>
                                <option value="429">Riau Satu</option>
                                <option value="265">Rienews</option>
                                <option value="160">Rimba News</option>
                                <option value="334">Rising Geeks</option>
                                <option value="772">Risk Id</option>
                                <option value="329">Roompi Id</option>
                                <option value="782">Ruang Harian</option>
                                <option value="309">Ruang Terang</option>
                                <option value="380">Ruangan Info</option>
                                <option value="453">Rubic News</option>
                                <option value="68">Sabakota Id</option>
                                <option value="853">Sagala News</option>
                                <option value="859">Sagaranesia</option>
                                <option value="921">Sahabat Semesta</option>
                                <option value="538">Saluran Media</option>
                                <option value="474">Sandaran Id</option>
                                <option value="83">Sangalu</option>
                                <option value="141">Santai Aja</option>
                                <option value="702">Sapa lombok</option>
                                <option value="123">Satu Arah</option>
                                <option value="814">Sawitku Id</option>
                                <option value="435">Sebekasi</option>
                                <option value="751">Sekala Media</option>
                                <option value="602">Selaparang News</option>
                                <option value="834">Selebriti Insider</option>
                                <option value="850">Selingkar Wilis</option>
                                <option value="936">Senang Senang</option>
                                <option value="968">Senayan Post</option>
                                <option value="875">Sepak Terjang</option>
                                <option value="158">Sepakbola Semarang</option>
                                <option value="909">Sepasi News</option>
                                <option value="472">Seputar Militer</option>
                                <option value="395">Seputar Nusa</option>
                                <option value="116">Setia Fakta</option>
                                <option value="153">Sewaktu</option>
                                <option value="618">Sewelaz</option>
                                <option value="617">Shiro Gadget</option>
                                <option value="650">Showbiz Indo</option>
                                <option value="184">Si Jogja</option>
                                <option value="793">Siar indo</option>
                                <option value="164">Siar Media</option>
                                <option value="848">Siber Kalimantan</option>
                                <option value="176">Siber Manado</option>
                                <option value="701">Siberita</option>
                                <option value="570">Sidak Post</option>
                                <option value="422">Sidik Jari</option>
                                <option value="688">Sidik Media</option>
                                <option value="471">Siger Media</option>
                                <option value="209">Sila News</option>
                                <option value="846">Sinar Editorial</option>
                                <option value="385">Sinar Harapan</option>
                                <option value="291">Sinar Jabar</option>
                                <option value="246">Sinar Kabar</option>
                                <option value="723">Sinar Lombok</option>
                                <option value="934">Sinar Merdeka</option>
                                <option value="1001">Sinaran Id</option>
                                <option value="549">Sinaran Update</option>
                                <option value="459">Sinarin</option>
                                <option value="487">Sinergi Jakarta</option>
                                <option value="286">Sinergi Jatim</option>
                                <option value="290">Sinergi Madura</option>
                                <option value="287">Sinergi Papers</option>
                                <option value="484">Singaparna Today</option>
                                <option value="608">Singaraja Post</option>
                                <option value="861">Sisi Jabar</option>
                                <option value="748">Situbondo Network</option>
                                <option value="14">Skor Id</option>
                                <option value="325">Sleman News</option>
                                <option value="71">Smol Id</option>
                                <option value="1010">Solusi Harian</option>
                                <option value="637">Soulsel</option>
                                <option value="156">Space Media</option>
                                <option value="894">Spasika</option>
                                <option value="612">Spirit Kepri</option>
                                <option value="402">Spirit Madura</option>
                                <option value="860">Spirit Rakyat</option>
                                <option value="355">Sporta News</option>
                                <option value="137">Sporty Life</option>
                                <option value="365">Storiloka</option>
                                <option value="559">Story Jatim</option>
                                <option value="104">Strategi</option>
                                <option value="535">Suara Buruh</option>
                                <option value="878">Suara Hits</option>
                                <option value="260">Suara Karya</option>
                                <option value="721">Suara Linggau</option>
                                <option value="4">Suara Merdeka</option>
                                <option value="824">Suara Merdeka Bali</option>
                                <option value="9">Suara Merdeka Banyumas</option>
                                <option value="17">Suara Merdeka Blora</option>
                                <option value="134">Suara Merdeka Jakarta</option>
                                <option value="16">Suara Merdeka Jepara</option>
                                <option value="18">Suara Merdeka Jogja</option>
                                <option value="898">Suara Merdeka Kabar Viral</option>
                                <option value="21">Suara Merdeka Kedu</option>
                                <option value="7">Suara Merdeka Muria</option>
                                <option value="6">Suara Merdeka Pantura</option>
                                <option value="181">Suara Merdeka Pekalongan</option>
                                <option value="19">Suara Merdeka Purworejo</option>
                                <option value="5">Suara Merdeka Solo</option>
                                <option value="976">Suara Merdeka Sport</option>
                                <option value="897">Suara Merdeka Terawang</option>
                                <option value="8">Suara Merdeka Wawasan</option>
                                <option value="20">Suara Merdeka Wonogiri</option>
                                <option value="333">Suara Muda</option>
                                <option value="767">Suara Nanggroe</option>
                                <option value="267">Suara Pantura</option>
                                <option value="847">Suara Perbatasan</option>
                                <option value="862">Suara Siantar</option>
                                <option value="513">Suara Sukabumi</option>
                                <option value="600">Suara Umat News</option>
                                <option value="375">Sudah Baca</option>
                                <option value="633">Sudut Lampung</option>
                                <option value="1004">Sugawa</option>
                                <option value="652">Sulawesi Network</option>
                                <option value="530">Sulbar Ekspres</option>
                                <option value="384">Sulsel Network</option>
                                <option value="388">Sultra Network</option>
                                <option value="419">Sultra Raya</option>
                                <option value="548">Suluh Desa</option>
                                <option value="643">Suluh Jateng</option>
                                <option value="680">Suluh Merdeka</option>
                                <option value="603">Sulut Network</option>
                                <option value="791">Sulut Zone</option>
                                <option value="932">Sumatera Insider</option>
                                <option value="609">Sumba Voice</option>
                                <option value="674">Sumenep Network</option>
                                <option value="328">Sumsel 24</option>
                                <option value="800">Sumut insider</option>
                                <option value="948">Sunda Urang</option>
                                <option value="904">Surabaya Insider</option>
                                <option value="52">Surabaya Network</option>
                                <option value="939">Surakarta Pos</option>
                                <option value="582">Swara Muda</option>
                                <option value="352">Swargantara</option>
                                <option value="522">Tajuk 24</option>
                                <option value="777">Tak Ada Jeda</option>
                                <option value="393">Tamiang Satu</option>
                                <option value="195">Tangerang Raya</option>
                                <option value="458">Technodition</option>
                                <option value="497">Tekno app</option>
                                <option value="719">Tekno Play</option>
                                <option value="413">Telegrafnesia</option>
                                <option value="108">Telusur News</option>
                                <option value="579">Tengganai</option>
                                <option value="457">Tentang</option>
                                <option value="726">Tentang Indonesia</option>
                                <option value="803">Teras info</option>
                                <option value="464">Teras Malioboro</option>
                                <option value="679">Teras Pulau</option>
                                <option value="489">Terbaik</option>
                                <option value="788">Terkini</option>
                                <option value="146">Teropong Dunia</option>
                                <option value="611">Teropong Jateng</option>
                                <option value="150">Teropong Politik</option>
                                <option value="410">Terpantau</option>
                                <option value="698">The Papua Jurnal</option>
                                <option value="925">Tiga Fase</option>
                                <option value="769">Tiga Pena</option>
                                <option value="421">Time Sumsel</option>
                                <option value="930">Time Today</option>
                                <option value="995">Timenews</option>
                                <option value="317">Tinemu</option>
                                <option value="185">TiNewss</option>
                                <option value="938">Tinjau Indonesia</option>
                                <option value="272">Tinta Putih</option>
                                <option value="112">Tipologi</option>
                                <option value="86">Titik Temu</option>
                                <option value="337">Top Media</option>
                                <option value="969">Topstories</option>
                                <option value="129">Tourism News</option>
                                <option value="491">Travelling</option>
                                <option value="823">Tred Media</option>
                                <option value="543">Trend Berita</option>
                                <option value="1022">Trending Sumsel</option>
                                <option value="740">Trenggalek Network</option>
                                <option value="586">Trixy</option>
                                <option value="763">Tuban Info</option>
                                <option value="735">Tuban Network</option>
                                <option value="801">Tudepoin</option>
                                <option value="739">Tulungagung Network</option>
                                <option value="594">Tutwuri Id</option>
                                <option value="973">Ukm Nusantara</option>
                                <option value="178">Umat Post</option>
                                <option value="288">Unews</option>
                                <option value="305">Urban Bandung</option>
                                <option value="311">Urban Bekasi</option>
                                <option value="268">Urban Bogor</option>
                                <option value="895">Urban Cianjur</option>
                                <option value="255">Urban Depok</option>
                                <option value="896">Urban Garut</option>
                                <option value="92">Urban Jabar</option>
                                <option value="691">Urban Jakarta</option>
                                <option value="692">Urban Jogja</option>
                                <option value="978">Urban Kota</option>
                                <option value="759">Vagansa</option>
                                <option value="440">Varta DIY</option>
                                <option value="977">Venomena</option>
                                <option value="213">Vespapedia</option>
                                <option value="331">Victory News</option>
                                <option value="339">Victory News Manggarai Barat</option>
                                <option value="342">Victory News Rote Ndao</option>
                                <option value="340">Victory News Sikka</option>
                                <option value="341">Victory News Sport</option>
                                <option value="399">Victory News Sultra</option>
                                <option value="343">Victory News Sumba Timur</option>
                                <option value="344">Victory News TTU</option>
                                <option value="807">View Jabar</option>
                                <option value="174">Views</option>
                                <option value="645">Viral Jambi</option>
                                <option value="843">Voice Sulawesi</option>
                                <option value="210">Volkpop</option>
                                <option value="913">Wacanan</option>
                                <option value="434">Wali Nusantara</option>
                                <option value="912">Wanodia</option>
                                <option value="790">Warga Desa</option>
                                <option value="545">Warna indonesia</option>
                                <option value="835">Warna Nusa</option>
                                <option value="534">Warta Favorit</option>
                                <option value="390">Warta Nasional</option>
                                <option value="590">Warta Pesona</option>
                                <option value="931">Warta Timor</option>
                                <option value="856">Wartanet News</option>
                                <option value="232">Wartechno</option>
                                <option value="503">Watyutink</option>
                                <option value="467">Wonosobo Zone</option>
                                <option value="598">Wow Babel</option>
                                <option value="840">Wow Basel</option>
                                <option value="839">Wow Belitung</option>
                                <option value="1033">Wow Indonesia</option>
                                <option value="841">Wow Sumsel</option>
                                <option value="687">Yogya Update</option>
                                <option value="941">YoKalbar</option>
                                <option value="254">Younity</option>
                                <option value="485">Youtuber</option>
                                <option value="357">Yuk Jelajah</option>
                                <option value="409">Zetizens</option>
                                <option value="923">Zona Baca</option>
                                <option value="120">Zona Bandung</option>
                                <option value="207">Zona Ekspos</option>
                                <option value="907">Zona Fakta</option>
                                <option value="673">Zona Jakarta</option>
                                <option value="1000">Zona Sports</option>
                            </select>
                        </div>
                        <div class="form-group">
                            <input id="input_search" type="text" class="form-control input-sm"
                                placeholder="Search..."
                                data-url="https://editor.promediateknologi.id/photo/index" data-query-string=""
                                value="">
                        </div>
                    </div>
                </div>
        </div>
        <div class="card-body">
            <div class="row mb-2">
                <h5>Pagination here</h5>
            </div>
            <div class="row box-photo-upload">
                <div class="row">
                    @for ($i=0; $i<15; $i++)
                    <div class="col-md-3 col-sm-4 col-xs-12" style="margin-bottom:10px">
                        <div class="img-thumbnail overlay-wrapper">
                            <img src="https://i.ytimg.com/vi/lJrIPXfZ1u0/mqdefault.jpg" alt="" class="img-responsive" title="도적: 칼의 소리 | 티저 예고편 | 넷플릭스">
                            <div style="margin-top:5px">
                                <strong><small title="24953">by: Disha KVIBES</small></strong>
                            </div>
                        </div>
                        
                        <div style="position:absolute;top:10px;margin-left:10px">                    
                                                    
                                <label class="label label-default">도적: 칼의…</label>
                                            </div>
                        <div style="position:absolute;bottom:35px;margin-left:10px">                    
                                                                    <a data-module="video/edit" class="btn btn-default btn-xs" href="https://editor.promediateknologi.id/video/edit/36836"><i class="fa fa-edit"></i> Edit</a>
                                                    
                                <a data-module="video/delete" class="btn btn-default btn-xs" href="https://editor.promediateknologi.id/video/delete/36836" onclick="return confirm('Delete this data ?')"><i class="fa fa-trash"></i> Delete</a>
                                            </div>
        
                    </div> 
                    @endfor
                </div>
            </div>
            <div class="row mt-2">
                <h5>Pagination here</h5>
            </div>
        </div>
    </div>
</x-app-layout>
